CREATE TABLE twitterer (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  account_id VARCHAR(50) NOT NULL UNIQUE,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE review (
  id SERIAL PRIMARY KEY,
  twitterer_id INTEGER NOT NULL REFERENCES twitterer(id),
  review_category_id INTEGER NOT NULL,
  value INTEGER NOT NULL,
  review_count INTEGER NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE twitterer_category (
  id SERIAL PRIMARY KEY,
  category_name VARCHAR(50) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE twitterer_category_list (
  id SERIAL PRIMARY KEY,
  twitterer_id INTEGER NOT NULL REFERENCES twitterer(id),
  twitterer_category_id INTEGER NOT NULL REFERENCES twitterer_category(id),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE current_topic (
  id SERIAL PRIMARY KEY,
  title VARCHAR(50) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE current_topic_comment (
  id SERIAL PRIMARY KEY,
  post_time TIMESTAMP,
  posted_name VARCHAR(50),
  comment VARCHAR(500) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE total_review (
  id SERIAL PRIMARY KEY,
  twitterer_id INTEGER NOT NULL REFERENCES twitterer(id),
  total_value INTEGER NOT NULL,
  review_count INTEGER NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE review_category (
  id SERIAL PRIMARY KEY,
  category_name VARCHAR(50) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE review_category_score_list (
  id SERIAL PRIMARY KEY,
  review_category_id INTEGER NOT NULL REFERENCES review_category(id),
  twitterer_id INTEGER NOT NULL REFERENCES twitterer(id),
  average_score INTEGER NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comment (
  id SERIAL PRIMARY KEY,
  twitterer_id INTEGER NOT NULL REFERENCES twitterer(id),
  post_time TIMESTAMP,
  posted_name VARCHAR(50),
  comment VARCHAR(500) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE server_config (
  id SERIAL PRIMARY KEY,
  parameter VARCHAR(50),
  memo VARCHAR(50),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);